@startuml

package burgerking {
    
    class Administrador {
        +Administrador(String user, String password)
        +trabajar(Sistema sistema) : boolean
    }

    class Bebida {
        -String sabor
        +Bebida()
        +getSabor() : String
        +setSabor(String sabor)
    }

    class Cocineros {
        +Cocineros(String user, String password)
        +trabajar(Sistema sistema) : boolean
    }

    class ControlIngreso {
        -Sistema sistema
        -String usuario
        -String contraseña
        -boolean validar
        +ingresar()
    }

    class EntradaSalida {
        +leerString(String texto) : String
        +leerNro(String texto) : int
        +siNo(String texto) : boolean
        +mostrarTexto(String texto)
        +menuAlta() : int
        +menuGerentes() : int
        +menuInspector() : int
        +limpiarPantalla()
    }

    class Gerentes {
        +Gerentes(String user, String password)
        +trabajar(Sistema sistema) : boolean
    }

    class Hamburguesa {
        -String combo
        -int carne
        -int cebolla
        -int lechuga
        -int tomate
        -int queso
        +Hamburguesa(String combo, int carne, int cebolla, int lechuga, int tomate, int queso)
        +getCarne() : int
        +setCarne(int carne)
        +getCebolla() : int
        +getCombo() : String
        +setCombo(String combo)
        +setCebolla(int cebolla)
        +getLechuga() : int
        +setLechuga(int lechuga)
        +getTomate() : int
        +setTomate(int tomate)
        +getQueso() : int
        +setQueso(int queso)
        +mostrarHamburguesa(StringBuilder sb)
    }

    class Inspectores {
        +Inspectores(String user, String password)
        +trabajar(Sistema sistema) : boolean
    }

    class Main {
        +main(String[] args)
    }

    class Papa {
        -String tamaño
        +Papa(String tamaño)
        +getTamaño() : String
        +setTamaño(String tamaño)
    }

    class Pedido {
        -String id
        -String cliente
        -LocalDate fecha
        -float precio
        -String estado
        -ArrayList<Hamburguesa> hamburguesas
        -ArrayList<Bebida> bebidas
        -ArrayList<Papa> papas
        +Pedido(String id)
        +getId() : String
        +setId(String id)
        +getFecha() : LocalDate
        +getHamburguesas() : ArrayList<Hamburguesa>
        +setHamburguesas(ArrayList<Hamburguesa> hamburguesas)
        +getBebidas() : ArrayList<Bebida>
        +setBebidas(ArrayList<Bebida> bebidas)
        +getPapas() : ArrayList<Papa>
        +setPapas(ArrayList<Papa> papas)
        +getPrecio() : float
        +setPrecio(float precio)
        +getEstado() : String
        +setEstado(String estado)
        +agregarCombo(String nombre, int carne, int cebolla, int lechuga, int tomate, int queso, String tamañoPapa, float precio)
        +getCliente() : String
        +setCliente(String cliente)
    }

    class Persona {
        -String user
        -String password
        +getUser() : String
        +getPassword() : String
        +setUser(String user)
        +setPassword(String password)
        +trabajar(Sistema sistema) : boolean
        +encontrarCredenciales(String credenciales) : boolean
    }

    class Sistema {
        -ArrayList<Persona> empleado
        -ArrayList<Pedido> pedidos
        +Sistema()
        +getEmpleado() : ArrayList<Persona>
        +setEmpleado(ArrayList<Persona> empleado)
        +deSerializar(String a) : Sistema
        +serializar(String a)
        +buscarUsuario(String credenciales) : Persona
        +validarIngreso(String user, String pass) : boolean
        +listaPorRoles(String referencia)
        +buscarPorRol(String usuario) : String
        +modificarRol(String user, String rol)
        +altaUsuario() : boolean
        +getPedidos() : ArrayList<Pedido>
        +setPedidos(ArrayList<Pedido> pedidos)
        +consultarPedidos(String estado)
        +mostrarPedidoPorId(String id)
        +actualizarComanda(String id)
        +obtenerListadoVentas()
        +obtenerListadoPedidosCompletos()
    }

    class Vendedor {
        +Vendedor(String user, String password)
        +trabajar(Sistema sistema) : boolean
        -tomarPedido(Sistema sistema)
        -modificarIngrediente(Hamburguesa hamburguesa, boolean agregar, Pedido pedido)
        -seleccionarBebida(Bebida bebida, Pedido pedido)
        -modificarTamañoPapas(Papa papa, Pedido pedido)
    }

    Persona <|-- Cocineros : "es un tipo de"
    Persona <|-- Gerentes : "es un tipo de"
    Persona <|-- Inspectores : "es un tipo de"
    Persona <|-- Vendedor : "es un tipo de"
    Persona <|-- Administrador : "es un tipo de"

    Pedido *-- Hamburguesa : "contiene"
    Pedido *-- Bebida : "contiene"
    Pedido *-- Papa : "contiene"
    Sistema o-- Persona : "emplea"
    Sistema o-- Pedido : "contiene"
    ControlIngreso *-- Sistema : "controla"
    Persona .. Sistema : "interactúa con"

}



@enduml
